name: Run build

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    harden_security:
        name: Check SHA in GH Actions
        runs-on: ubuntu-latest
        steps:
            - name: "Checking-out code"
              uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v3
            - name: "Ensure SHA pinned actions"
              uses: zgosalvez/github-actions-ensure-sha-pinned-actions@0b552a197e44b819629237e065d781f5ca691460 # v1.1.1
    lint:
        name: "Lint"
        runs-on: ubuntu-latest

        steps:
            - name: "Checking-out code"
              uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v3
              with:
                  fetch-depth: 0
            - name: "Defining node version"
              uses: actions/setup-node@5b52f097d36d4b0b2f94ed6de710023fbb8b2236 # v3
              with:
                  node-version-file: ".nvmrc"
                  cache: "npm"
                  cache-dependency-path: "**/package-lock.json"
            - name: "Installing dependencies"
              run: npm run bootstrap
            - name: "Linting code (MR)"
              if: github.event_name == 'pull_request'
              run: npm run lint -- --since origin/${{ github.base_ref }}
            - name: "Linting code"
              if: github.event_name != 'pull_request'
              run: npm run lint
    test:
        name: "Unit tests"
        runs-on: ubuntu-latest

        steps:
            - name: "Checking-out code"
              uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v3
              with:
                  fetch-depth: 0
            - name: "Defining node version"
              uses: actions/setup-node@5b52f097d36d4b0b2f94ed6de710023fbb8b2236 # v3
              with:
                  node-version-file: ".nvmrc"
                  cache: "npm"
                  cache-dependency-path: "**/package-lock.json"
            - name: "Installing dependencies"
              run: npm run bootstrap
            - name: "Running unit tests (MR)"
              if: github.event_name == 'pull_request'
              run: npm run test -- --since origin/${{ github.base_ref }}
            - name: "Running unit tests"
              if: github.event_name != 'pull_request'
              run: npm run test
    build:
        name: "Build for ${{ matrix.target }} target on ${{ matrix.os }}"
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
                target: [build, release]

        steps:
            - name: "Checking-out code"
              uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v3
              with:
                  fetch-depth: 0
            - name: "Defining node version"
              uses: actions/setup-node@5b52f097d36d4b0b2f94ed6de710023fbb8b2236 # v3
              with:
                  node-version-file: ".nvmrc"
                  cache: "npm"
                  cache-dependency-path: "**/package-lock.json"
            - name: "Installing dependencies"
              run: npm run bootstrap
            - name: "Running build for development (MR)"
              if: github.event_name == 'pull_request'
              run: npm run build -- --since origin/${{ github.base_ref }}
              env:
                  NODE_OPTIONS: --max_old_space_size=8192
            - name: "Running build for development"
              if: github.event_name != 'pull_request'
              run: npm run ${{ matrix.target }}
              env:
                  NODE_OPTIONS: --max_old_space_size=8192
    script-tests:
        name: "Script tests (Node ${{ matrix.node }}, ${{ matrix.os }})"
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node: [16]
                os: [windows-latest, ubuntu-latest]
                include:
                    - node: 14
                      os: ubuntu-latest
                      experimental: true
        steps:
            - name: "Checking-out code"
              uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v3
              with:
                  fetch-depth: 0
            - name: "Defining node version"
              uses: actions/setup-node@5b52f097d36d4b0b2f94ed6de710023fbb8b2236 # v3
              with:
                  node-version: ${{ matrix.node }}
                  cache: "npm"
                  cache-dependency-path: "**/package-lock.json"
            - name: "Installing dependencies"
              run: npm run bootstrap
            - name: Increase number of watchers
              if: startsWith(matrix.os, 'ubuntu')
              run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
            - name: "Running build for development (MR)"
              if: github.event_name == 'pull_request'
              run: npm run test:scripts -- --since origin/${{ github.base_ref }}
            - name: "Running build for development"
              if: github.event_name != 'pull_request'
              run: npm run test:scripts
