name: Run native automated end-to-end tests for Android

on:
    workflow_dispatch:

    pull_request:
        branches: [master]

jobs:
    native_automated_tests_android:
        name: "Native automated tests for Android"
        runs-on: linux-latest
        permissions:
            packages: read
            contents: read
        steps:
            - name: "Checking-out code"
              uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2
              with:
                  submodules: false
            - name: "Fetching master to compare"
              if: github.event_name == 'pull_request'
              run:
                  git fetch --no-tags --prune --depth=1 origin +refs/heads/${{ github.base_ref
                  }}:refs/remotes/origin/${{ github.base_ref }}
            - name: "Defining cache"
              uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed # v2
              env:
                  cache-name: cache-node-modules
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
            - name: "Defining node version"
              uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 # v2
              with:
                  node-version: "16"
            - name: Login to GitHub Container Registry
              uses: docker/login-action@42d299face0c5c43a0487c477f595ac9cf22f1a7 # v1.12.0
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: "Installing dependencies"
              run: npm install
            - name: "Start Mendix Environment & run tests"
              env:
                  BROWSERSTACK_USERNAME: ${{ secrets.BrowserstackUsername }}
                  BROWSERSTACK_ACCESS_KEY: ${{ secrets.BrowserstackAccessKey }}
              run: node ./scripts/test/e2e-native.js
            - name: "Archive test screenshot diff results"
              uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2
              if: failure()
              with:
                  name: test-screenshot-results
                  path: |
                      ${{ github.workspace }}/packages/**/e2e/images/diffs/**/*.png
                  if-no-files-found: error
